yarnPath: .yarn/releases/yarn-3.5.0.cjs
# Some packages may require unlisted dependencies and fail in yarn strict mode.
# If your need to fix this, activate the loose mode.
pnpMode: loose

# Some tools don't work at all under Plug'n'Play environments, ex. React Native
# and Flow. In such a radical case, you can enable the built-in node-modules plugin.
# This will cause Yarn to install the project just like Yarn 1 used to, by 
# copying the packages into various node_modules folders.
# nodeLinker: node-modules